### ISSUE TITLE
Installation in shared file system

### ISSUE THREAD

**Issue by marchoeppner** [standage/AEGeAn#124]
Hi, not an 'issue' as such, but I was wondering why the Makefile of AEDeAn uses a hard-coded location for installation, specifically /usr/local . I am trying to install this package in a shared cluster environment and man this is frustrating. Wouldn't it be an option to pass a prefix to the Makefile? Likewise, why is there a strict expectation that genometools be installed in the same location? It wouldn't be difficult too just pass the library files via LD_LIBRARY_PATH during compilation - instead all that stuff is hardcoded too. 

Any chance that this will be improved in the future?

**Comment by standage** [comment]
Thanks for the note.

The hard-coded installation directory is a default, and is easily overridden on the command line: see (the installation instructions)[http://aegean.readthedocs.org/en/v0.10.2/install.html#compiling-and-installing].

As far as the assumption that AEGeAn and GenomeTools be installed to the same directory, that was a design decision made earlier in development to simplify the compiling process. I'm open to improvements, so if you would like to submit a pull request I would be happy to review and integrate it.
