### ISSUE TITLE
GFF parsing

### ISSUE THREAD

**Issue by alpapan** [standage/AEGeAn#153]
Dear Daniel

is it possible to support double newlines (i.e. empty line) as a GFF record separator please (on top of the existing ###)?

e.g.

<code>
NW_004522754.1  JAMg    gene    118683  120968  .       +       .       ID=evm.TU.NW_004522754.1.2;Name=JAMg_NW_004522754.1.2
NW_004522754.1  JAMg    mRNA    118683  120968  .       +       .       ID=evm.model.NW_004522754.1.2;Parent=evm.TU.NW_004522754.1.2;Name=JAMg_NW_004522754.1.2
NW_004522754.1  JAMg    exon    118683  120968  .       +       .       ID=evm.model.NW_004522754.1.2.exon1;Parent=evm.model.NW_004522754.1.2
NW_004522754.1  JAMg    CDS     118683  120968  .       +       0       ID=cds.evm.model.NW_004522754.1.2;Parent=evm.model.NW_004522754.1.2

NW_004522754.1  JAMg    gene    141343  142821  .       -       .       ID=evm.TU.NW_004522754.1.3;Name=JAMg_NW_004522754.1.3
NW_004522754.1  JAMg    mRNA    141343  142821  .       -       .       ID=evm.model.NW_004522754.1.3;Parent=evm.TU.NW_004522754.1.3;Name=JAMg_NW_004522754.1.3
NW_004522754.1  JAMg    exon    141343  141746  .       -       .       ID=evm.model.NW_004522754.1.3.exon3;Parent=evm.model.NW_004522754.1.3
NW_004522754.1  JAMg    exon    141810  142708  .       -       .       ID=evm.model.NW_004522754.1.3.exon2;Parent=evm.model.NW_004522754.1.3
NW_004522754.1  JAMg    exon    142763  142821  .       -       .       ID=evm.model.NW_004522754.1.3.exon1;Parent=evm.model.NW_004522754.1.3
NW_004522754.1  JAMg    CDS     141343  141746  .       -       1       ID=cds.evm.model.NW_004522754.1.3;Parent=evm.model.NW_004522754.1.3
NW_004522754.1  JAMg    CDS     141810  142708  .       -       2       ID=cds.evm.model.NW_004522754.1.3;Parent=evm.model.NW_004522754.1.3
NW_004522754.1  JAMg    CDS     142763  142821  .       -       0       ID=cds.evm.model.NW_004522754.1.3;Parent=evm.model.NW_004522754.1.3
</code>

Thank you!
alexie

**Comment by standage** [comment]
AEGeAn uses the [GenomeTools](http://github.com/genometools/genometools) GFF3 parsing machinery, so any changes would need to be suggested and implemented there. I'm guessing this would be an easy task, technically, but there are probably concerns. For instance, there are probably empty lines in many GFF3 files that are not intended as record separators. So then we would have to make this a configurable option, which complicates the API. I'm not sure how eager I or the core GenomeTools devs would be to support this...
