### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by alpapan** [standage/AEGeAn#154]
Hello

Using Genometools 1.5.5 (as recommended on docs), it seems to fail to compile (i may be doing smth wrong).

Genometools compiled/installed OK (with cairo=no)

$ make prefix=`pwd`/../ cairo=no 64bit=yes

[compile AgnAttributeFilterStream]
[compile AgnCliquePair]
[compile AgnCompareReportHTML]
src/core/AgnCompareReportHTML.c: In function ‘compare_report_html_locus_handler’:
src/core/AgnCompareReportHTML.c:492:5: error: implicit declaration of function ‘agn_locus_print_png’ [-Werror=implicit-function-declaration]
     agn_locus_print_png(locus, rpt->pngdata);
     ^
cc1: all warnings being treated as errors
make: *** [obj/AgnCompareReportHTML.o] Error 1

With errorcheck=no
obj/AgnCompareReportHTML.o: In function `compare_report_html_locus_handler':
/home/alexie/software/git/JAMg/3rd_party/AEGeAn-0.14.1/src/core/AgnCompareReportHTML.c:492: undefined reference to `agn_locus_print_png'
/home/alexie/software/git/JAMg/3rd_party/AEGeAn-0.14.1/..//lib/libgenometools.so: undefined reference to `dlopen'
/home/alexie/software/git/JAMg/3rd_party/AEGeAn-0.14.1/..//lib/libgenometools.so: undefined reference to `dlclose'
/home/alexie/software/git/JAMg/3rd_party/AEGeAn-0.14.1/..//lib/libgenometools.so: undefined reference to `dlerror'
/home/alexie/software/git/JAMg/3rd_party/AEGeAn-0.14.1/..//lib/libgenometools.so: undefined reference to `dlsym'

any ideas? could it be the GT version? I tried with GT 1.5.2 (cairo=no 64bit=yes) and got the same error

**Comment by alpapan** [comment]
the above report was for the latest stable release (14.1); works fine with the master HEAD.....

**Comment by standage** [comment]
Thanks for the report!

Indeed, this bug has been fixed since v0.14.1 and will be released with the next stable release.
