### ISSUE TITLE
src/core/AgnTranscriptClique.c

### ISSUE THREAD

**Issue by alpapan** [standage/AEGeAn#155]
Hello

This happens using a particular prediction set. It was created via WebApollo so it may have a bug from the export. How can we debug it?

Assertion failed: (gt_range_contains(&locusrange, &transrange) && gt_range_length(&locusrange) == strlen(modelvector)), function clique_vector_update, file src/core/AgnTranscriptClique.c, line 539.
This is a bug, please report it at https://github.com/standage/AEGeAn/issues.

thanks
a

**Comment by alpapan** [comment]
Command was 
~/software/JAMg/3rd_party/bin/parseval -d -V -x NCBI -y CURATIONS ncbi.gff3.canon annotations.gff.Approved_Accepted.cleanedup.gff3.canon > CURATIONS_VS_NCBI.txt

**Comment by alpapan** [comment]
Ignore me, this is almost certainly a bug from somewhere upstream... sorry!

**Comment by alpapan** [comment]
i'm sorry, but this still happens even after i solved all the upstream issues i could think.

it also happens in the reciprocal search.

If it was possible to print which loci are being compared (with the debug flag) then it would be easier to find out what is happening

**Comment by alpapan** [comment]
Hello
Found that with a very high --delta (800) the crash goes away. so I manually identified 5 genes (out of 1400) that caused the error. they are good proteins so i don't know why that happened. let me know if you'd like the files.
thanks
a

**Comment by standage** [comment]
Indeed, it would be much easier for me to help you debug if you posted your small (5 genes) data set.

**Comment by alpapan** [comment]
thnx, emailed!

**Comment by standage** [comment]
Ok, sorry for the delayed response. I've had a look at the example data you provided, and it's failing on a gene where the range of the `mRNA` feature extends beyond the range of the `gene` feature (NW_004523309.1 from 9714850 to 9718050).

So this is clearly a problem with the data file (and probably WebApollo's GFF3 export feature). But ParsEval should do a better job of handling this. I'll work on a fix for this soon.

**Comment by standage** [comment]
I just pushed a new commit to the master branch. Please let me know if this solves your problem.

**Comment by standage** [comment]
I'm going to go ahead and close this issue. Feel free to open it if you are still experiencing related issues.
